default_language_version:
  python: python3.11
repos:
- repo: local
  hooks:
  - id: end-of-file-fixer
    entry: end-of-file-fixer
    language: system
    name: end-of-file-fixer
  - id: trailing-whitespace
    entry: trailing-whitespace-fixer
    language: system
    name: trailing-whitespace
    exclude: ^.*\.md$

  - id: ruff
    entry: ruff check --fix
    require_serial: true
    language: system
    name: ruff
    types: [ python ]
  - id: ruff-format
    entry: ruff format
    require_serial: true
    language: system
    name: ruff-format
    types: [ python ]

  - id: mypy
    entry: mypy --strict
    require_serial: true
    language: system
    name: mypy
    types: [ python ]
